### ISSUE TITLE
####

### ISSUE THREAD

**Issue by trqt** [rEiNbU-gAi/MasterProgramBot#1]

**Comment by Arka-Night** [comment]
;-;

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Guilherme Corrêa Torquato <notifications@github.com>
Enviado: Wednesday, May 6, 2020 8:33:02 PM
Para: rEiNbU-gAi/MasterProgramBot <MasterProgramBot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [rEiNbU-gAi/MasterProgramBot] Saudades (#1)


😔✊
